/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BottomNavigation: typeof import('./components/BottomNavigation.vue')['default']
    copy: typeof import('./components/Weather copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Weather: typeof import('./components/Weather.vue')['default']
    WeatherCard: typeof import('./components/WeatherCard.vue')['default']
    WeatherHistory: typeof import('./components/WeatherHistory.vue')['default']
    WeatherSearch: typeof import('./components/WeatherSearch.vue')['default']
  }
}
